### ISSUE TITLE
Missing code

### ISSUE THREAD

**Issue by tuscland** [slburson/misc-extensions#1]
Hello Scott,

I wanted to clone the misc-extensions repository, but could not find the code.
There is a repository on GitHub, but it is not yours:
https://github.com/VincentToups/misc-extensions

I know I can install this library with Quicklisp, but I would like to avoid it this time.

Best,
Cam

**Comment by slburson** [comment]
I don't know Vincent Toups, but that is my library.  He doesn't appear to
have modified it -- at least, there's only one commit in this repo.

I'll try to get my copy up sometime this weekend.

-- Scott

On Sat, Mar 22, 2014 at 3:45 AM, Camille Troillard <notifications@github.com
